
enum ECategoryType {
    News = "News",
    Discussion = "Discussion",
    Training = "Training",
    Races = "Races",
    Gear = "Gear",
    Live = "Live",
}

enum ETrendType {
    Hot = "Hot",
    Latest = "Latest",
    Following = "Following",
    Others = "Others",
}

enum EContinent {
    Africa = "africa",
    Asia = "asia",
    Europe = "europe",
    NorthAmerica = "north-america",
    Oceania = "oceania",
    SouthAmerica = "south-america",
    Top = "top",
}

enum EAfrica {
    Algeria = "Algeria",
    Angola = "Angola",
    Benin = "Benin",
    Botswana = "Botswana",
    BurkinaFaso = "Burkina Faso",
    Burundi = "Burundi",
    CaboVerde = "CaboVerde",
    Cameroon = "Cameroon",
    CentralAfricanRepublic = "Central African Republic",
    Chad = "Chad",
    Comoros = "Comoros",
    DemocraticRepublicOfTheCongo = "Democratic Republic Of The Congo",
    RepublicOfTheCongo = "Republic Of The Congo",
    IvoryCoast = "Ivory Coast",
    Djibouti = "Djibouti",
    Egypt = "Egypt",
    EquatorialGuinea = "Equatorial Guinea",
    Eritrea = "Eritrea",
    Eswatini = "Eswatini",
    Ethiopia = "Ethiopia",
    Gabon = "Gabon",
    Gambia = "Gambia",
    Ghana = "Ghana",
    Guinea = "Guinea",
    GuineaBissau = "Guinea Bissau",
    Kenya = "Kenya",
    Lesotho = "Lesotho",
    Liberia = "Liberia",
    Libya = "Libya",
    Madagascar = "Madagascar",
    Malawi = "Malawi",
    Mali = "Mali",
    Mauritania = "Mauritania",
    Mauritius = "Mauritius",
    Morocco = "Morocco",
    Mozambique = "Mozambique",
    Namibia = "Namibia",
    Niger = "Niger",
    Nigeria = "Nigeria",
    Rwanda = "Rwanda",
    SaoTomeAndPrincipe = "Sao Tome And Principe",
    Senegal = "Senegal",
    Seychelles = "Seychelles",
    SierraLeone = "Sierra Leone",
    Somalia = "Somalia",
    SouthAfrica = "South Africa",
    Sudan = "Sudan",
    SouthSudan = "South Sudan",
    Tanzania = "Tanzania",
    Togo = "Togo",
    Tunisia = "Tunisia",
    Uganda = "Uganda",
    Zambia = "Zambia",
    Zimbabwe = "Zimbabwe",
}

enum ENorthAmerica {
    AntiguaAndBarbuda = "Antigua and Barbuda",
    Bahamas = "The Bahamas",
    Barbados = "Barbados",
    Belize = "Belize",
    Canada = "Canada",
    CostaRica = "Costa Rica",
    Cuba = "Cuba",
    Dominica = "Dominica",
    DominicanRepublic = "Dominican Republic",
    ElSalvador = "El Salvador",
    Grenada = "Grenada",
    Guatemala = "Guatemala",
    Haiti = "Haiti",
    Honduras = "Honduras",
    Jamaica = "Jamaica",
    Mexico = "Mexico",
    Nicaragua = "Nicaragua",
    Panama = "Panama",
    SaintKittsAndNevis = "Saint Kitts and Nevis",
    SaintLucia = "SaintLucia",
    SaintVincentAndTheGrenadines = "Saint Vincent and the Grenadines",
    TrinidadAndTobago = "Trinidad and Tobago",
    UnitedStates = "United States",
}

enum ESouthAmerica {
    Argentina = "Argentina",
    Bolivia = "Bolivia",
    Brazil = "Brazil",
    Chile = "Chile",
    Colombia = "Colombia",
    Ecuador = "Ecuador",
    Guyana = "Guyana",
    Paraguay = "Paraguay",
    Peru = "Peru",
    Suriname = "Suriname",
    Uruguay = "Uruguay",
    Venezuela = "Venezuela",
}

enum EAsia {
    Afghanistan = "Afghanistan",
    Armenia = "Armenia",
    Azerbaijan = "Azerbaijan",
    Bahrain = "Bahrain",
    Bangladesh = "Bangladesh",
    Bhutan = "Bhutan",
    Brunei = "Brunei",
    Cambodia = "Cambodia",
    China = "China",
    Cyprus = "Cyprus",
    Georgia = "Georgia",
    India = "India",
    Indonesia = "Indonesia",
    Iran = "Iran",
    Iraq = "Iraq",
    Israel = "Israel",
    Japan = "Japan",
    Jordan = "Jordan",
    Kazakhstan = "Kazakhstan",
    Kuwait = "Kuwait",
    Kyrgyzstan = "Kyrgyzstan",
    Laos = "Laos",
    Lebanon = "Lebanon",
    Malaysia = "Malaysia",
    Maldives = "Maldives",
    Mongolia = "Mongolia",
    Myanmar = "Myanmar",
    Nepal = "Nepal",
    NorthKorea = "NorthKorea",
    SouthKorea = "SouthKorea",
    Oman = "Oman",
    Pakistan = "Pakistan",
    Palestine = "Palestine",
    Philippines = "Philippines",
    Qatar = "Qatar",
    SaudiArabia = "SaudiArabia",
    Singapore = "Singapore",
    SriLanka = "SriLanka",
    Syria = "Syria",
    Tajikistan = "Tajikistan",
    Thailand = "Thailand",
    TimorLeste = "TimorLeste",
    Turkmenistan = "Turkmenistan",
    Turkey = "Turkey",
    UnitedArabEmirates = "UnitedArabEmirates",
    Uzbekistan = "Uzbekistan",
    Vietnam = "Vietnam",
    Yemen = "Yemen",
}

enum EEurope {
    Albania = "Albania",
    Andorra = "Andorra",
    Armenia = "Armenia",
    Austria = "Austria",
    Azerbaijan = "Azerbaijan",
    Belarus = "Belarus",
    Belgium = "Belgium",
    BosniaAndHerzegovina = "Bosnia and Herzegovina",
    Bulgaria = "Bulgaria",
    Croatia = "Croatia",
    Cyprus = "Cyprus",
    CzechRepublic = "Czech Republic",
    Denmark = "Denmark",
    Estonia = "Estonia",
    Finland = "Finland",
    France = "France",
    Georgia = "Georgia",
    Germany = "Germany",
    Greece = "Greece",
    Hungary = "Hungary",
    Iceland = "Iceland",
    Ireland = "Ireland",
    Italy = "Italy",
    Kazakhstan = "Kazakhstan",
    Kosovo = "Kosovo",
    Latvia = "Latvia",
    Liechtenstein = "Liechtenstein",
    Lithuania = "Lithuania",
    Luxembourg = "Luxembourg",
    NorthMacedonia = "North Macedonia",
    Malta = "Malta",
    Moldova = "Moldova",
    Monaco = "Monaco",
    Montenegro = "Montenegro",
    Netherlands = "Netherlands",
    Norway = "Norway",
    Poland = "Poland",
    Portugal = "Portugal",
    Romania = "Romania",
    Russia = "Russia",
    SanMarino = "San Marino",
    Serbia = "Serbia",
    Slovakia = "Slovakia",
    Slovenia = "Slovenia",
    Spain = "Spain",
    Sweden = "Sweden",
    Switzerland = "Switzerland",
    Turkey = "Turkey",
    Ukraine = "Ukraine",
    UnitedKingdom = "United Kingdom",
}

enum EOceania {
    Australia = "Australia",
    Fiji = "Fiji",
    Kiribati = "Kiribati",
    MarshallIslands = "Marshall Islands",
    Micronesia = "Micronesia",
    Nauru = "Nauru",
    NewZealand = "New Zealand",
    Palau = "Palau",
    PapuaNewGuinea = "Papua New Guinea",
    Samoa = "Samoa",
    SolomonIslands = "Solomon Islands",
    Tonga = "Tonga",
    Tuvalu = "Tuvalu",
    Vanuatu = "Vanuatu",
}

enum ETop {
    Belgium = "Belgium",
    Brazil = "Brazil",
    China = "China",
    France = "France",
    Italy = "Italy",
    Netherlands = "Netherlands",
    Portugal = "Portugal",
    Spain = "Spain",
    UnitedKingdom = "United Kingdom",
    UnitedStates = "United States",
}

export {
    ECategoryType,
    EContinent,
    ETrendType,
    EAfrica,
    EAsia,
    ENorthAmerica,
    ESouthAmerica,
    EEurope,
    EOceania,
    ETop,
}
